# StopEnderThief Configuration
# 是否启用插件功能
enabled: true

# 调试模式 - 启用后会在控制台输出详细的调试信息
debug: false

# 消息配置
messages:
  plugin-enabled: "&a[StopEnderThief] 插件已启用！"
  plugin-disabled: "&c[StopEnderThief] 插件已禁用！"
  config-reloaded: "&a[StopEnderThief] 配置文件已重新加载！"
  debug-enabled: "&a[StopEnderThief] 调试模式已启用！"
  debug-disabled: "&c[StopEnderThief] 调试模式已禁用！"
  no-permission: "&c你没有权限执行此命令！"
